// function
import * as React from 'react';
import styled from 'styled-components';


interface MainHeaderProps {
};

const StyledMainHeader = styled.div<MainHeaderProps>`
    width: 100%;
    height: 5vh;
    position: absolute;
    top: 0;
    left: 0;
    border-bottom: 1px solid #999999;
`

const StyledTitle = styled.title`
    display: block;
    font-size: 10px;
    color: black;
    width: 100%;
`
const MainHeader: React.FC<MainHeaderProps> = () =>
<StyledMainHeader> 
    <StyledTitle>test mojo</StyledTitle>
    <StyledTitle>Create Next App</StyledTitle>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
</StyledMainHeader>

export default MainHeader;
