import * as React from 'react';
import styled from 'styled-components';


interface MainHeaderProps {
    text: String,
};

const StyledMainHeader = styled.div`
    width: 100%;
    height: 150px;
    position: absolute;
    top: 0;
    left: 0;
    display:flex;
    border-bottom: 1px solid #eeeeee;
    align-items: center;
`

const StyledTitle = styled.title`
    display: block;
    font-size: 30px;
    color: #666666;
    font-weight: 400;
    width: 100%;
    text-align: center;
`
const ImageBox = styled.img`
    display: block;
    width: 30px;
    height: 24px;
    margin: auto 40px;
`
const MarginBox = styled.div`
    display: block;
    width: 30px;
    height: 24px;
    margin: auto 40px;
`

const MainHeader: React.FC<MainHeaderProps> = (props) => {
    const {text} = props;
    return (
        <StyledMainHeader>
            {/* <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" /> */}
            <ImageBox src="/images/svg/list-button.svg"></ImageBox>
            <StyledTitle>{text}</StyledTitle>
            <MarginBox></MarginBox>
        </StyledMainHeader>)
    }

export default MainHeader;
